/* Lightweight, real-material specimens; no iframes, network assets or full demos. */
(() => {
  'use strict';
  const profiles = window.UI_PREVIEW_PROFILES;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const repeat = (count, fn) => Array.from({length:count}, (_,i) => fn(i)).join('');
  const bar = (text, right='STUDIO / 01') => `<div class="pv-top"><b>${text}</b><span>${right}</span></div>`;
  const pill = (text, extra='') => `<span class="pv-pill ${extra}">${text}</span>`;
  const lines = '<div class="pv-lines"><i></i><i></i><i></i></div>';
  const chart = (forecast=false) => `<svg class="pv-chart" viewBox="0 0 320 92" fill="none"><path class="pv-chart-grid" d="M0 20H320M0 50H320M0 80H320"/><path class="pv-chart-area" d="M0 77L30 68L55 72L80 46L106 57L137 36L162 43L191 20L220 31L250 15L280 24L320 4V92H0Z"/><path class="pv-chart-line" d="${forecast?'M0 77L30 68L55 72L80 46L106 57L137 36L162 43L191 20':'M0 77L30 68L55 72L80 46L106 57L137 36L162 43L191 20L220 31L250 15L280 24L320 4'}"/>${forecast?'<path class="pv-confidence" d="M191 20L320 0V58L191 20Z"/><path class="pv-forecast-line" d="M191 20L220 31L250 15L280 24L320 4"/>':''}</svg>`;
  const wave = () => `<div class="pv-wave">${repeat(23,i=>`<i style="--h:${12+Math.round(Math.abs(Math.sin(i*1.8))*51)}px;--delay:${i*-.08}s"></i>`)}</div>`;
  const dial = label => `<div class="pv-dial"><div><small>${label}</small><strong>72<span>°</span></strong></div></div>`;
  const plant = '<div class="pv-plant"><i></i><i></i><i></i><i></i><b></b></div>';
  const radar = '<div class="pv-radar"><i></i><i></i><b></b><em></em></div>';
  const table = (labels=['Brand system','Mobile app','Website']) => `<div class="pv-table">${labels.map((s,i)=>`<div><span>${s}</span><i class="pv-status">${['In progress','Review','Completed'][i%3]}</i><b>${[86,62,100][i%3]}%</b></div>`).join('')}</div>`;
  const dataHead = (title,number,sub='↑ 18.6% this month') => `${bar(title,'OVERVIEW') }<div class="pv-data-title"><strong>${number}</strong><small>${sub}</small></div>`;
  const renders = {
    swiss: () => `${bar('FORM.','DESIGN INDEX — 001')}<div class="pv-swiss-copy"><small>LESS, BUT BETTER.</small><strong>Make<br>room.</strong><p>A little space. A clearer idea.</p>${pill('Explore collection ↗')}</div><div class="pv-swiss-art"><i></i><b>01</b></div><div class="pv-baseline">OBJECTS / SPACE / IDEAS <span>EST. 2026</span></div>`,
    soft: () => `${bar('Atmosphere','HOME CONTROL')}<div class="pv-soft-card">${dial('ROOM TEMP')}<div class="pv-soft-side"><small>Living room</small><strong>Just right.</strong><div class="pv-soft-track"><i></i></div><div class="pv-soft-keys"><span>−</span><span>+</span></div></div></div><div class="pv-soft-foot"><span>Auto climate</span><i class="pv-toggle"></i></div>`,
    glass: () => `<div class="pv-glass-orbs"><i></i><i></i><i></i></div><div class="pv-glass-back"></div><div class="pv-glass-card">${bar('aura.','MEMBERSHIP')}<span class="pv-glass-label">YOUR CREATIVE SPACE</span><strong>Beyond<br>the surface.</strong><div class="pv-glass-bottom"><span>•••• 2084</span><b>↗</b></div></div><div class="pv-floating-chip">✦ Made of light</div>`,
    rawweb: () => `${bar('NOT A TEMPLATE.','[ MENU ]')}<div class="pv-raw-title">THIS IS<br>A WEBSITE.</div><div class="pv-raw-rule"></div><div class="pv-raw-bottom"><p>No polish.<br>Just the essentials.</p><span>ENTER SITE →</span></div><small class="pv-raw-code">&lt;body&gt; content, not decoration. &lt;/body&gt;</small>`,
    product: () => `${bar('SOLID / OBJECTS','VOL. 01')}<div class="pv-product-title"><small>LIGHT & MATERIAL</small><strong>A new<br>dimension.</strong>${pill('Discover ↗')}</div><div class="pv-object-scene"><div class="pv-torus"></div><div class="pv-object-shadow"></div><span>FORM No. 08</span></div>`,
    blocks: () => `<div class="pv-block-grid"><div><b>PLAY<br>IT BIG.</b><small>IDEAS WITHOUT LIMITS</small></div><div><i class="pv-flower">✳</i></div><div><span>01 / CREATE</span><b>↗</b></div><div><span>Make your<br>next move.</span><i>●</i></div></div>`,
    oled: () => `${bar('NOCTURNE','● CONNECTED')}<div class="pv-oled-player"><div class="pv-record"></div><div><small>NOW PLAYING</small><strong>After hours</strong><span>Quiet nights · 04:28</span><div class="pv-player-controls">‹ <b>Ⅱ</b> ›</div></div></div><div class="pv-track"><i></i></div><div class="pv-player-times"><span>02:16</span><span>04:28</span></div>`,
    accessible: () => `${bar('Clear.','ACCESS FOR EVERYONE')}<div class="pv-access"><strong>A clearer way<br>to get things done.</strong><div class="pv-access-field"><span>Full name</span><b>Alex Morgan<span>│</span></b></div><div class="pv-access-action">Continue <b>→</b><small>Enter ↵</small></div><p>✓ Saved securely <span>Text + icon feedback</span></p></div>`,
    clay: () => `${bar('little wins','DAILY GOALS')}<div class="pv-clay-star">✦</div><div class="pv-clay-card"><small>YOU'RE DOING GREAT</small><strong>One step<br>at a time.</strong><div class="pv-clay-progress"><i></i></div>${pill('Keep going ↗')}</div><div class="pv-clay-bubble">7<small>day streak</small></div>`,
    aurora: () => `<div class="pv-aurora-light"></div>${bar('LUMEN','AN OPEN INVITATION')}<div class="pv-aurora-copy"><small>WHERE IDEAS COME ALIVE</small><strong>Meet the<br>extraordinary.</strong>${pill('Explore the unknown ↗')}</div><div class="pv-aurora-line">LIGHT / SPACE / POSSIBILITY</div>`,
    retro: () => `${bar('FUTURE SYSTEMS','1984 / ONLINE')}<div class="pv-crt"><div class="pv-retro-sun"></div><strong>THE FUTURE<br>IS LOADING_</strong><span>[■■■■■■■■□□□□] 68%</span></div><div class="pv-retro-strip">FREQUENCY 108.8 <span>▶ PLAY / REWIND ◀</span></div>`,
    flat: () => `${bar('Daylight','YOUR DAILY SPACE')}<div class="pv-flat-heading"><strong>Less busy.<br>More done.</strong><span>◒</span></div><div class="pv-flat-tiles"><div><b>▦</b><span>Projects</span></div><div><b>✓</b><span>Completed</span></div><div><b>↗</b><span>Insights</span></div></div>`,
    material: () => `<div class="pv-radio"><div class="pv-radio-label">ANALOG / FM STEREO</div><div class="pv-radio-face"><div class="pv-radio-speaker"></div><div class="pv-radio-controls"><div class="pv-frequency"><span>88　 96　 104　108</span><i></i><b>FM 102.4</b></div><div class="pv-radio-knobs"><i></i><i></i></div></div></div><div class="pv-radio-bottom">TUNE INTO SOMETHING REAL <span>● POWER</span></div></div>`,
    liquid: () => `<div class="pv-liquid-land"><i></i><b></b></div><div class="pv-liquid-time">09:41<small>Tuesday, September 24</small></div><div class="pv-liquid-widget"><b>21°</b><span>Mostly clear<br><small>H: 24°　L: 17°</small></span></div><div class="pv-liquid-dock"><span>◉</span><span>♫</span><span>⌕</span><span>☼</span></div>`,
    motion: () => `${bar('MOMENTUM','HOVER TO PLAY')}<div class="pv-motion-copy"><small>DESIGNED TO MOVE</small><strong>Keep<br>moving.</strong></div><div class="pv-motion-path"><i></i><i></i><i></i><b>↗</b></div><div class="pv-motion-timeline"><span>01 — START</span><i></i><span>02 — NEXT</span></div>`,
    micro: () => `${bar('Small details.','BIG DIFFERENCE')}<div class="pv-micro-grid"><div><span class="pv-heart">♡</span><small>A little delight</small></div><div><i class="pv-toggle"></i><small>Always in sync</small></div><div class="pv-micro-save"><b>✓</b><span>All changes saved</span></div></div><div class="pv-micro-progress"><i></i></div><small class="pv-micro-note">EVERY ACTION DESERVES A RESPONSE.</small>`,
    inclusive: () => `${bar('Everyone.','MADE FOR ALL')}<div class="pv-inclusive-body"><strong>Your way<br>to connect.</strong><div class="pv-inclusive-options"><span>▤<b>Read</b></span><span>♫<b>Listen</b></span><span>Aa<b>Large text</b></span></div><div class="pv-inclusive-status">✓ Ready to continue <b>→</b></div></div>`,
    ambient: () => `${bar('here.','JUST ASK')}<div class="pv-ambient-orb"></div><div class="pv-ambient-copy"><strong>Already taken care of.</strong><p>Your room is just how you like it.</p><small>22° · Soft light · Quiet moments</small></div>`,
    soft2: () => `${bar('Balance','A LITTLE MORE CLARITY')}<div class="pv-soft-evolution"><div><small>TODAY'S FOCUS</small><strong>Find your<br>flow state.</strong>${pill('Start session ↗')}</div><div class="pv-soft-ring">25<small>minutes</small></div></div><div class="pv-soft-summary"><b>○ Deep work</b><span>4 sessions this week</span></div>`,
    dashboard: () => `${bar('Workspace analytics','7 DAYS ▾')}<div class="pv-kpis">${['24,680','84.2%','1,208'].map((s,i)=>`<div><small>${['Visitors','Completion','Active users'][i]}</small><b>${s}</b><span>↑ ${12+i*3}.4%</span></div>`).join('')}</div><div class="pv-dense-bottom"><div>${chart()}</div><div class="pv-mini-bars">${repeat(8,i=>`<i style="height:${20+(i*19)%68}px"></i>`)}</div></div>${table(['Project alpha','Project beta'])}`,
    heatmap: () => `${bar('Activity map','LAST 12 WEEKS')}<div class="pv-heat-title"><strong>Every day counts.</strong><span>1,284 contributions</span></div><div class="pv-heat-layout"><div class="pv-heat-labels">MON<br>WED<br>FRI</div><div class="pv-heat-matrix">${repeat(91,i=>`<i style="opacity:${.12+((i*19+i%4*7)%10)*.088}"></i>`)}</div></div><div class="pv-heat-legend"><span>Less</span>${repeat(5,i=>`<i style="opacity:${.15+i*.2}"></i>`)}<span>More</span></div>`,
    executive: () => `${bar('Business at a glance','Q3 / OVERVIEW')}<div class="pv-exec-main"><small>TOTAL REVENUE</small><strong>$1.28M</strong><span>↗ 24.6% above last quarter</span></div><div class="pv-exec-bottom"><div><small>Customers</small><b>12,480</b></div><div><small>Retention</small><b>96.2%</b></div><div><small>Growth</small><b>+28%</b></div></div>`,
    monitor: () => `${bar('SYSTEM / LIVE','● ALL SYSTEMS NORMAL')}<div class="pv-monitor-head"><strong>99.98<small>%</small></strong><span>UPTIME<br><b>24ms latency</b></span></div><svg class="pv-monitor-wave" viewBox="0 0 350 60"><path d="M0 35H38L46 30L51 39L61 7L70 57L82 35H135L144 22L153 41L161 10L174 51L185 35H243L255 25L263 44L274 3L282 55L293 35H350"/></svg><div class="pv-monitor-log"><span>12:08:24　api-gateway</span><b>HEALTHY</b><span>12:08:23　database</span><b>HEALTHY</b></div>`,
    drill: () => `${bar('Explore revenue','FILTERS ⌄')}<div class="pv-breadcrumb">All regions <span>›</span> Europe <span>›</span> <b>Germany</b></div><div class="pv-drill-title"><strong>€248,600</strong><span>↑ 18.2%</span></div><div class="pv-drill-tree"><div>⌄ Europe <b>€842,000</b></div><div>　⌄ Germany <b>€248,600</b></div><div>　　 Berlin <b>€128,400</b></div><div>　　 Munich <b>€120,200</b></div></div>`,
    compare: () => `${bar('Performance comparison','THIS MONTH / LAST MONTH')}<div class="pv-comparison-head"><span><i></i> This period <b>24,680</b></span><span><i></i> Previous <b>19,420</b></span></div><div class="pv-paired-bars">${repeat(5,i=>`<div><i style="height:${46+i*14}px"></i><i style="height:${30+i*12}px"></i><small>${['Mon','Tue','Wed','Thu','Fri'][i]}</small></div>`)}</div>`,
    forecast: () => `${dataHead('Revenue forecast','$124,600','NEXT QUARTER · ESTIMATE')}<div class="pv-forecast-chart">${chart(true)}<div class="pv-forecast-divider"></div></div><div class="pv-forecast-legend"><span>━ Observed</span><span>┄ Forecast</span><span>▰ Confidence range</span></div>`,
    funnel: () => `${bar('Conversion journey','USER FLOW')}<div class="pv-funnel-shape">${['Visitors','Engaged','Checkout','Converted'].map((s,i)=>`<div style="--fw:${100-i*19}%"><span>${s}</span><b>${['12,480','8,640','4,210','1,280'][i]}</b></div>`).join('')}</div><small class="pv-funnel-note">VISIT → ENGAGE → ACT → CONVERT</small>`,
    finance: () => `${dataHead('Financial overview','$284,680.00','↑ 12.8% net balance')}<div class="pv-finance-row"><span>Income <b>+$42,680</b></span><span>Expenses <b>−$18,240</b></span></div>${chart()}<div class="pv-finance-footer"><span>Cash flow</span><b>Jan　Feb　Mar　Apr　May　Jun</b></div>`,
    sales: () => `${bar('Sales pipeline','THIS QUARTER')}<div class="pv-sales-target"><b>$186,400</b><span>78% of target</span></div><div class="pv-sales-progress"><i></i></div><div class="pv-sales-columns">${['Qualified','Proposal','Won'].map((s,i)=>`<div><small>${s} <b>${[12,8,5][i]}</b></small><article><b>${['Acme Inc.','Northstar','Orbit'][i]}</b><span>$${[24,18,32][i]},000</span></article><article><b>${['Linear Co.','Forma','Monograph'][i]}</b><span>$${[12,28,16][i]},000</span></article></div>`).join('')}</div>`,
    neo: () => `${bar('OFFBEAT®','NOT YOUR AVERAGE.')}<div class="pv-neo-sticker">✳</div><div class="pv-neo-copy"><strong>GOOD<br>DIFFERENT.</strong><p>Stand out. Stay yourself.</p>${pill('LET’S MAKE THINGS ↗')}</div><span class="pv-neo-label">100% ORIGINAL</span>`,
    bento: () => `<div class="pv-bento-grid"><div><small>ALL IN ONE PLACE</small><strong>A space<br>for every idea.</strong><span>↗</span></div><div><b>12.8k</b><small>Creative minds</small></div><div><i>✳</i></div><div><span>Weekly momentum</span><div class="pv-bento-bars">${repeat(6,i=>`<i style="height:${10+i*7}px"></i>`)}</div></div></div>`,
    y2k: () => `${bar('CYBER ANGEL ✧','ONLINE SINCE 2000')}<div class="pv-y2k-star">✧</div><div class="pv-y2k-title">dream<br>in digital.</div><div class="pv-y2k-orb"></div>${pill('ENTER MY WORLD ♡')}<span class="pv-y2k-note">★ NEW MILLENNIUM ENERGY ★</span>`,
    cyber: () => `${bar('NEXUS // 2077','NETRUNNER ONLINE')}<div class="pv-cyber-heading"><small>ACCESS LEVEL : 04</small><strong>JACK<br>IN.</strong></div><div class="pv-cyber-panel"><small>NEURAL LINK</small><b>98.4%</b>${wave()}<span>ENCRYPTION ACTIVE</span></div><div class="pv-cyber-footer">[ CONNECT TO NETWORK ] <b>→</b></div>`,
    organic: () => `${bar('fern & form','GROW AT YOUR OWN PACE')}${plant}<div class="pv-organic-copy"><small>ROOM TO BREATHE</small><strong>A little<br>closer to nature.</strong>${pill('Find your calm ↗')}</div>`,
    ai: () => `${bar('orbit ✳','YOUR THINKING PARTNER')}<div class="pv-ai-conversation"><small>YOU</small><p>Make room for a better idea.</p><div><b>✳</b><span>Let's explore a few possibilities.<br><i>Thoughtfully built, just for you.</i></span></div></div><div class="pv-ai-chips"><span>Explore ideas</span><span>Make a plan</span></div><div class="pv-ai-input">Ask anything… <b>↑</b></div>`,
    memphis: () => `<div class="pv-memphis-pattern"><i>〰</i><i>△</i><i>•••</i><i>⌁</i></div><div class="pv-memphis-card"><small>MAKE SOME NOISE</small><strong>OH,<br>HAPPY DAY!</strong>${pill('LET’S PLAY →')}</div><div class="pv-memphis-circle"></div>`,
    vapor: () => `${bar('ＰＡＲＡＤＩＳＥ','FM 1992')}<div class="pv-vapor-sun"></div><div class="pv-vapor-grid"></div><div class="pv-vapor-copy"><strong>ＥＳＣＡＰＥ</strong><span>somewhere between then & now</span></div><div class="pv-vapor-player">◀　Ⅱ　▶ <span>ＳＬＯＷ ＤＲＥＡＭＳ</span></div>`,
    layers: () => `${bar('LAYERS','A DIFFERENT PERSPECTIVE')}<div class="pv-layer-card pv-layer-back"><span>01 / FOUNDATION</span></div><div class="pv-layer-card pv-layer-mid"><span>02 / STRUCTURE</span></div><div class="pv-layer-card pv-layer-front"><small>03 / YOUR NEXT IDEA</small><strong>Depth makes<br>the difference.</strong><span>Bring it forward ↗</span></div>`,
    bigtype: () => `${bar('ESSENTIAL.','NO MORE. NO LESS.')}<div class="pv-bigtype-word">Less.</div><div class="pv-bigtype-foot"><span>Everything you need.<br>Nothing you don't.</span><b>↗</b></div>`,
    kinetic: () => `${bar('TYPE IN MOTION','HOVER / EXPERIMENT 01')}<div class="pv-kinetic-word">MAKE<br><em>IT MOVE.</em></div><div class="pv-kinetic-marquee">NOTHING STANDS STILL — NOTHING STANDS STILL —</div>`,
    story: () => `<div class="pv-story-sky"></div><div class="pv-story-moon"></div><div class="pv-story-mountain back"></div><div class="pv-story-mountain front"></div>${bar('FIELD NOTES','CHAPTER 01')}<div class="pv-story-title"><small>BEYOND THE EVERYDAY</small><strong>A world<br>worth exploring.</strong></div><div class="pv-story-bottom">SCROLL TO DISCOVER <span>↓</span></div>`,
    swiss2: () => `${bar('INTERNATIONAL / 02','NEW PERSPECTIVES')}<div class="pv-swiss2-grid"><div><b>Type.<br>Space.<br>Order.</b><small>DESIGN IS A SYSTEM.</small></div><div><span>02</span><i></i></div></div><div class="pv-swiss2-foot">ZÜRICH — 2026 <span>FORM FOLLOWS FUNCTION ↗</span></div>`,
    hud: () => `${bar('AEGIS / COMMAND','SECTOR 07')}${radar}<div class="pv-hud-readouts"><small>SCANNING AREA</small><b>084.72</b><span>RANGE / 2.8 KM</span><i></i><small>TARGET ACQUIRED</small><b>12 : 08</b></div><div class="pv-hud-footer">SYS.READY <span>■■■■■□□□　62%</span></div>`,
    pixel: () => `${bar('PIXEL QUEST','HI-SCORE 024800')}<div class="pv-pixel-scene"><div class="pv-pixel-heart">${repeat(49,i=>`<i class="${['0110110','1111111','1111111','0111110','0011100','0001000','0000000'][Math.floor(i/7)][i%7]==='1'?'on':''}"></i>`)}</div><strong>LEVEL UP!</strong><p>YOUR NEXT ADVENTURE AWAITS</p>${pill('PRESS START ▸')}</div><div class="pv-pixel-ground"></div>`,
    spatial: () => `<div class="pv-spatial-room"></div><div class="pv-spatial-panel">${bar('Moments','◉')}<div><b>A little<br>more space.</b><span>Open a new perspective.</span></div><div class="pv-spatial-tiles"><i></i><i></i><i></i></div></div><div class="pv-spatial-dock"><span>⌂</span><span>▦</span><span>♫</span><span>✳</span></div>`,
    paper: () => `${bar('THE QUIET READER','ISSUE No. 24')}<div class="pv-paper-article"><small>ON THE ART OF SLOW LIVING</small><h3>The beauty<br>of doing less.</h3><p>Some things are worth slowing down for. A good book, a quiet morning, a little room to think.</p></div><div class="pv-paper-foot"><span>CHAPTER ONE</span><span>12 / 84　→</span></div>`,
    chaos: () => `<div class="pv-chaos-checks"></div><div class="pv-chaos-a">WHY<br>NOT?</div><div class="pv-chaos-b">more is<br><u>MORE.</u></div><div class="pv-chaos-c">☺</div><div class="pv-chaos-d">MAKE A LITTLE MESS ↗</div><div class="pv-chaos-e">★</div><span class="pv-chaos-label">NO RULES CLUB / 002</span>`,
    bio: () => `${bar('SYMBIOSIS','A LIVING SYSTEM')}<div class="pv-bio-cells">${repeat(6,i=>`<i style="--i:${i}"></i>`)}</div><div class="pv-bio-copy"><small>INSPIRED BY LIFE</small><strong>Always<br>evolving.</strong><span>GROWTH INDEX　+24.8%</span></div>`,
    sketch: () => `${bar('a work in progress.','IDEAS WELCOME')}<div class="pv-sketch-note"><span class="pv-tape"></span><small>note to self:</small><strong>Make something<br>imperfect.</strong><u>and make it yours.</u><span class="pv-sketch-arrow">↗</span></div><div class="pv-sketch-spark">✳</div><span class="pv-sketch-foot">a little less polished. a little more human.</span>`,
    tactile: () => `${bar('SQUISH.','PLEASE DO TOUCH')}<div class="pv-jelly"><strong>Press<br>for joy.</strong><span>✳</span></div><div class="pv-jelly-small">↗</div><div class="pv-jelly-foot">SOFT THINGS. GOOD FEELINGS.</div>`,
    nature: () => `${bar('TERRA','NATURALLY CONSIDERED')}<div class="pv-nature-arch">${plant}<div class="pv-vase"></div></div><div class="pv-nature-copy"><small>ROOTED IN THE EVERYDAY</small><strong>A softer<br>kind of living.</strong>${pill('Explore the collection ↗')}</div>`,
    cursor: () => `${bar('STUDIO / INTERACTIVE','MOVE TO EXPLORE')}<div class="pv-cursor-title">Follow<br>your curiosity.</div><div class="pv-cursor-target"><b>↗</b></div><div class="pv-cursor-pointer"><svg viewBox="0 0 24 28"><path d="M2 2L21 15L12 17L8 26Z"/></svg><span>EXPLORE</span></div><div class="pv-cursor-trail"></div>`,
    voice: () => `${bar('Hello, again.','VOICE + TEXT')}<div class="pv-voice-copy"><small>LISTENING TO YOU</small><strong>What's on your mind?</strong></div>${wave()}<div class="pv-voice-caption">“Find a little time to focus.”</div><div class="pv-voice-controls"><span>Aa</span><b>Ⅱ</b><span>×</span></div>`,
    productview: () => `${bar('OBJECT / 008','DESIGNED TO BE HELD')}<div class="pv-productview-object"><div class="pv-torus"></div></div><div class="pv-productview-orbit"></div><div class="pv-productview-text"><small>THE EVERYDAY OBJECT</small><strong>Form, refined.</strong></div><div class="pv-productview-controls"><span>↻ 360° VIEW</span><div><i></i><i></i><i></i></div><b>+</b></div>`,
    mesh: () => `<div class="pv-mesh-bg"></div>${bar('CHROMA.','IN FULL SPECTRUM')}<div class="pv-mesh-copy"><small>COLOR WITHOUT BOUNDARIES</small><strong>Feel<br>everything.</strong>${pill('Step into the spectrum ↗')}</div>`,
    magazine: () => `${bar('THE FORM JOURNAL','DESIGN & CULTURE / 06')}<div class="pv-mag-head"><strong>Objects<br>of everyday.</strong><small>LESSONS IN<br>LOOKING CLOSER.</small></div><div class="pv-mag-columns"><div><b>A</b> different way to see the ordinary. Finding beauty in the spaces between things.</div><div class="pv-mag-photo"><i></i></div><div>Small details.<br>Lasting impressions.<br><br>READ THE STORY ↗</div></div>`,
    glitch: () => `${bar('SIGNAL / LOST','RGB CHANNEL ERROR')}<div class="pv-glitch-title">NO<br>SIGNAL.</div><div class="pv-glitch-band"></div><div class="pv-glitch-bottom"><span>R / G / B</span><b>[ RECONNECT ↗ ]</b></div>`,
    vintage: () => `${bar('SLOW DAYS','A MOMENT, KEPT')}<div class="pv-polaroid"><div class="pv-film-photo"><i></i><b></b></div><span>somewhere, someday.</span></div><div class="pv-vintage-copy"><small>COLLECT MOMENTS</small><strong>Stay<br>a little<br>longer.</strong><span>35 MM / VOL. 04</span></div>`,
    bauhaus: () => `${bar('BAUHAUS','FORM & FUNCTION')}<div class="pv-bauhaus-title">KUNST<br>UND<br>TECHNIK.</div><div class="pv-bauhaus-art"><i></i><b></b><em></em></div><div class="pv-bauhaus-foot">WEIMAR / DESSAU / BERLIN <span>1919 →</span></div>`,
    fluent: () => `${bar('▦ Workspace','⌕ Search')}<div class="pv-system-layout"><aside><b>◈ Home</b><span>▤ Documents</span><span>◷ Recent</span><span>☆ Favorites</span></aside><div><strong>Good morning, Alex</strong><div class="pv-system-command"><span>＋ New</span><span>↑ Upload</span></div><div class="pv-file-tiles"><i>▤<span>Brief.docx</span></i><i>▧<span>Ideas.pptx</span></i></div><small>RECOMMENDED FOR YOU</small>${lines}</div></div>`,
    polaris: () => `${bar('● Store admin','⌕ Search')}<div class="pv-polaris-body"><strong>Good morning, Studio.</strong><div class="pv-polaris-metrics"><span>Total sales<b>$4,280</b></span><span>Orders<b>128</b></span><span>Conversion<b>4.8%</b></span></div><div class="pv-polaris-task"><b>12 orders to fulfill</b><span>View orders →</span></div><small>RECENT ORDERS</small>${table(['#1048　Alex','#1047　Morgan'])}</div>`,
    spectrum: () => `${bar('◩ Design workspace','Share ↗')}<div class="pv-spectrum-workspace"><aside>↖<br>□<br>○<br>T<br>⌕</aside><div class="pv-spectrum-art"><i></i><b>Make<br>your mark.</b><span class="pv-selection"></span></div><section><small>PROPERTIES</small><span>Transform</span><b>W　240<br>H　180</b><span>Appearance</span><i></i></section></div>`,
    spectrum2: () => `${bar('✳ Your creative space','Create ＋')}<div class="pv-spectrum2-head"><strong>A fresh start<br>for your next idea.</strong><span>✳</span></div><div class="pv-spectrum2-tiles"><div><i>◒</i><b>Design</b></div><div><i>✦</i><b>Explore</b></div><div><i>↗</i><b>Create</b></div></div>`
  };
  function phone(kind) {
    const screens = {
      paper: '<small>THE DAILY NOTE</small><h3>Less,<br>but better.</h3><p>A quiet place for your thoughts.</p><hr><b>01 / Journal</b><hr><b>02 / Reading</b><div class="pv-ph-bottom">START READING ↗</div>',
      cinema: '<small>TONIGHT / CURATED</small><h3>Beyond<br>the frame.</h3><div class="pv-ph-poster"><i></i><span>AFTER<br>HOURS</span></div><div class="pv-ph-bottom">▶　Continue watching</div>',
      boutique: '<small>YOUR WORKSPACE</small><h3>Do your<br>best work.</h3><div class="pv-ph-metric"><span>This week</span><b>+28.4%</b></div><div class="pv-ph-card">✦　A little more focus</div><div class="pv-ph-bottom">Start something new ＋</div>',
      terminal: '<small>root@pocket:~$</small><h3>SYSTEM<br>READY_</h3><p>&gt; checking connection<br><b>[OK]</b> secure channel<br><br>&gt; loading workspace<br><b>[OK]</b> all systems go</p><div class="pv-ph-bottom">$ run next_</div>',
      kinetic: '<small>NO STANDING STILL</small><h3>MAKE<br>YOUR<br>MOVE.</h3><div class="pv-ph-marquee">GO. GO. GO. GO.</div><div class="pv-ph-bottom">LET’S DO THIS ↗</div>',
      flat: '<small>MONDAY, 24 SEPT</small><h3>Your day.<br>Your pace.</h3><div class="pv-ph-flat"><span>▦<b>Projects</b></span><span>✓<b>Done</b></span></div><div class="pv-ph-card">＋　Add a new task</div><div class="pv-ph-bottom">⌂　　 ▦　　 ○</div>',
      material: '<small>MY EVERYDAY</small><h3>Hello,<br>good day.</h3><div class="pv-ph-material-shapes"><span>✳</span><b>7.2k<small>steps today</small></b></div><div class="pv-ph-card">✓　Keep a little balance</div><div class="pv-ph-bottom">⌂　Home　　 ♡　You</div>',
      neo: '<small>HEY, YOU!</small><h3>MAKE<br>IT COUNT.</h3><div class="pv-ph-neo-sticker">✳</div><div class="pv-ph-card">✓　3 out of 5 goals</div><div class="pv-ph-bottom">KEEP GOING →</div>',
      poster: '<small>EDITION / 001</small><h3>BIG<br>IDEAS.<br>SMALL<br>SCREEN.</h3><div class="pv-ph-bottom">EXPLORE THE ISSUE ↗</div>',
      academia: '<small>THE PRIVATE LIBRARY</small><h3>A world<br>between<br>the pages.</h3><div class="pv-ph-book">THE ART<br>OF READING</div><div class="pv-ph-bottom">Continue reading　→</div>',
      hud: '<small>DECKER // ONLINE</small><h3>SECTOR<br>07.04</h3>'+radar+'<div class="pv-ph-bottom">SCAN COMPLETE　98%</div>',
      wallet: '<small>TOTAL BALANCE</small><h3>$28,460<span>.80</span></h3><div class="pv-ph-coin">₿</div><div class="pv-ph-card">Bitcoin <b>+4.28%</b></div><div class="pv-ph-bottom">↑ Send　　　 ↓ Receive</div>',
      clay: '<small>LITTLE DAILY WINS</small><h3>You’re<br>a star!</h3><div class="pv-ph-clay-star">★</div><div class="pv-ph-card">7 days of good habits</div><div class="pv-ph-bottom">Keep it up ↗</div>',
      enterprise: '<small>TEAM WORKSPACE</small><h3>Everything,<br>on track.</h3><div class="pv-ph-metric"><span>Project progress</span><b>84.2%</b></div><div class="pv-ph-card">●　Design review</div><div class="pv-ph-card">◷　Weekly planning</div><div class="pv-ph-bottom">⌂　　 ▦　　 ◯</div>',
      sketch: '<small>little things to do</small><h3>Let’s make<br>today good.</h3><div class="pv-ph-note"><span class="pv-tape"></span>☑ take a walk<br>☐ make something<br>☐ call a friend</div><div class="pv-ph-bottom">＋ one more idea</div>',
      soft: '<small>NOW PLAYING</small><div class="pv-ph-soft-disc">♫</div><h3>Soft moments</h3><p>Calm sounds, clear mind.</p><div class="pv-soft-track"><i></i></div><div class="pv-ph-soft-controls"><span>‹</span><b>Ⅱ</b><span>›</span></div>'
    };
    if (!screens[kind]) throw new Error(`Missing phone specimen: ${kind}`);
    return `<div class="pv-phone pv-phone-${kind}"><div class="pv-phone-status"><span>9:41</span><span>••• ▰</span></div><div class="pv-phone-content">${screens[kind]}</div><div class="pv-phone-home"></div></div><div class="pv-phone-caption"><span>MOBILE<br>EXPERIENCE</span><i></i><strong>${{paper:'Quiet.<br>Considered.',cinema:'Lights off.<br>World on.',boutique:'Work,<br>beautifully.',terminal:'Less chrome.<br>More code.',kinetic:'Never<br>stand still.',flat:'Keep it<br>simple.',material:'Express<br>yourself.',neo:'Bold by<br>nature.',poster:'Type<br>takes over.',academia:'A pocket<br>library.',hud:'A future<br>in your hand.',wallet:'Digital.<br>Distinct.',clay:'A little<br>softer.',enterprise:'A clearer<br>workday.',sketch:'Made<br>by hand.',soft:'Feel the<br>difference.'}[kind]}</strong><small>TOUCH-FIRST / 01</small></div>`;
  }
  function render(style, mode=style.defaultMode) {
    const p = profiles[style.id];
    if (!p) throw new Error(`Missing preview profile: ${style.id}`);
    const r = {...style.recipe,...style.modes[mode]};
    const content = p.kind.startsWith('phone-') ? phone(p.kind.slice(6)) : renders[p.kind]?.();
    if (!content) throw new Error(`Missing preview renderer: ${p.kind}`);
    const vars = `--p-bg:${r.bg};--p-surface:${r.surface};--p-ink:${r.ink};--p-muted:${r.muted};--p-accent:${r.accent};--p-accent2:${r.accent2};--p-line:${r.line};--p-radius:${r.radius}`;
    return `<div class="style-specimen" data-preview-id="${style.id}" role="img" aria-label="${esc(p.name+'：'+p.tags.join('、'))}"><div class="pv-canvas pv-${p.kind} ${p.kind.startsWith('phone-')?'pv-mobile':''}" data-mode="${mode}" style="${vars}" aria-hidden="true">${content}</div></div>`;
  }
  const observer = new ResizeObserver(entries => {
    for (const {target,contentRect} of entries) {
      if (contentRect.width) target.style.setProperty('--pv-scale', String(contentRect.width / 400));
    }
  });
  function mount() {
    observer.disconnect();
    document.querySelectorAll('.style-specimen').forEach(node => {
      const width=node.getBoundingClientRect().width;
      if (width) node.style.setProperty('--pv-scale',String(width/400));
      observer.observe(node);
    });
  }
  window.UIStylePreviews = {render,mount,kinds:Object.keys(renders)};
})();
